OP2 Sprint 1
green-fox-academy/opencv-rueppelli-2 pull request #11
Opened 2019-02-01 19:33 UTC by Dextyh

2019-02-03 22:30 UTC, leventekobor requested changes
Overall great work. 
For the folder strcutre I would suggest a change:
```
files
src (here comes all the cpp and hpp files from files)
gtest
img
docs
README.md
.
.
.
```

2019-02-03 22:30 UTC, leventekobor commented on Computer_Vision/CMakeLists.txt
>  endif()
missing new line at the end of a file

2019-02-03 22:30 UTC, leventekobor commented on Computer_Vision/files/CMakeLists.txt
> +add_library(project_files sqlite_functions.cpp sqlite_functions.h detect_circle.cpp detect_circle.h blur.cpp blur.h)
missing a new line at the end of a file

2019-02-03 22:30 UTC, leventekobor commented on Computer_Vision/files/blur.cpp
> +#include "blur.h"
I would not make a separate file for this. We are going to blur every image so this functionality has a nice place in the main. Also here we just warp the `cv` functions to our own `void` functions.

2019-02-03 22:30 UTC, leventekobor commented on Computer_Vision/files/detect_circle.cpp
> +    if(!image.empty()) {
why check if the image is empty here? We already check that in main

2019-02-03 22:30 UTC, leventekobor commented on Computer_Vision/files/detect_circle.cpp
> +        cvtColor(image, gray, cv::COLOR_BGR2GRAY);
we could simply load the picture in greyscale in the main

2019-02-03 22:30 UTC, leventekobor commented on Computer_Vision/files/detect_circle.cpp
> +    return -1;
or we could just return the `numberOfCircles` here

2019-02-03 22:30 UTC, leventekobor commented on Computer_Vision/files/sqlite_functions.cpp
> +
why so many new lines at the end of a file?

2019-02-03 22:30 UTC, leventekobor commented on Computer_Vision/files/sqlite_functions.h
> +#endif
missing a new line at the end of a file

2019-02-03 22:30 UTC, leventekobor commented on Computer_Vision/gtest/unit_test.cpp
>  }
missing a new line here as well

2019-02-03 22:30 UTC, leventekobor commented on Computer_Vision/main.cpp
> +    if(argc > 1) {
why check `argc` here?

2019-02-03 22:30 UTC, leventekobor reviewed
Also to the testing part. I know I was not specific but I require way more tests there.

2019-02-04 12:41 UTC, Dextyh commented on Computer_Vision/main.cpp
> +    if(argc > 1) {
DONE

2019-02-04 12:41 UTC, Dextyh commented on Computer_Vision/gtest/unit_test.cpp
>  }
DONE

2019-02-04 12:41 UTC, Dextyh commented on Computer_Vision/files/sqlite_functions.h
> +#endif
DONE

2019-02-04 12:41 UTC, Dextyh commented on Computer_Vision/files/sqlite_functions.cpp
> +
DONE

2019-02-04 12:42 UTC, Dextyh commented on Computer_Vision/files/detect_circle.cpp
> +    return -1;
DONE

2019-02-04 12:42 UTC, Dextyh commented on Computer_Vision/files/detect_circle.cpp
> +        cvtColor(image, gray, cv::COLOR_BGR2GRAY);
DONE

2019-02-04 12:42 UTC, Dextyh commented on Computer_Vision/files/detect_circle.cpp
> +    if(!image.empty()) {
DONE

2019-02-04 12:42 UTC, Dextyh commented on Computer_Vision/files/blur.cpp
> +#include "blur.h"
DONE

2019-02-04 12:42 UTC, Dextyh commented on Computer_Vision/files/CMakeLists.txt
> +add_library(project_files sqlite_functions.cpp sqlite_functions.h detect_circle.cpp detect_circle.h blur.cpp blur.h)
DONE

2019-02-04 12:42 UTC, Dextyh commented on Computer_Vision/CMakeLists.txt
>  endif()
DONE

2019-02-04 18:55 UTC, leventekobor approved these changes

2019-02-05 14:06 UTC, merged